default: &default
  adapter: postgresql
  adapter: postgresql
  host:    localhost
  encoding: unicode
  pool:     5

development:
  <<: *default
  database: game_bowling_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: game_bowling_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: game_bowling_prod
